apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-one
  labels:
    app: app-one
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-one
  template:
    metadata:
      labels:
        app: app-one
    spec:
      containers:
        - name: app-one
          image: wil42/playground:v1
          ports:
            - containerPort: 8888
              name: http-web-svc

---

apiVersion: v1
kind: Service
metadata:
  name: app-one
spec:
  # type: LoadBalancer
  type: NodePort
  # loadBalancerIP: 127.0.0.1
  # externalIPs:
  #  - 127.0.0.1
  selector:
    app: app-one
  ports:
    - name: name-of-service-port
      protocol: TCP
      port: 8888
      targetPort: http-web-svc


---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minimal-ingress
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: app-one
            port:
              number: 8888
